### ISSUE TITLE
C++ error

### ISSUE THREAD

**Issue by urielsinger** [luckiezhou/DynamicTriad#8]
Hey,

I'm getting the following error trying to run the code:

UserWarning: dynamic_triad_cimpl.so not found, falling back to python implementation
  warnings.warn("dynamic_triad_cimpl.so not found, falling back to python implementation")
Traceback (most recent call last):
  File "DynamicTriad/core/__init__.py", line 178, in <module>
    main()
  File "DynamicTriad/core/__init__.py", line 100, in main
    edgecnt = [g.num_edges() for g in ds.gtgraphs]
  File "/home/thisistheend/DynamicTriad/core/utils_py.py", line 189, in next
    ret = self._load_item(self.__iter)
  File "/home/thisistheend/DynamicTriad/core/utils_py.py", line 196, in _load_item
    self.__items[step - self.offset] = self.__factory(step)
  File "/home/thisistheend/DynamicTriad/core/dataset/dataset_utils.py", line 109, in <lambda>
    lambda i: gconv.mygraph2graphtool(self._mygraphs[i], convert_to='undirected'))
  File "/home/thisistheend/DynamicTriad/core/utils_py.py", line 159, in __getitem__
    return self._load_item(key)
  File "/home/thisistheend/DynamicTriad/core/utils_py.py", line 196, in _load_item
    self.__items[step - self.offset] = self.__factory(step)
  File "/home/thisistheend/DynamicTriad/core/dataset/dataset_utils.py", line 107, in <lambda>
    self._mygraphs = utils.OffsetList(self.localstep, self.nsteps, lambda step: self._load_graph(step))
  File "/home/thisistheend/DynamicTriad/core/dataset/dataset_utils.py", line 128, in _load_graph
    graphs.append(self._load_unit_graph(self._unit2time(u)))
  File "/home/thisistheend/DynamicTriad/core/dataset/adjlist.py", line 41, in _load_unit_graph
    g = mgutils.load_adjlist(fn)
  File "/home/thisistheend/DynamicTriad/core/mygraph_utils.py", line 85, in load_adjlist
    g = mygraph.Graph(node_type, weight_type)
Boost.Python.ArgumentError: Python argument types in
    Graph.__init__(Graph, str, str)
did not match C++ signature:
    __init__(_object*, int, int)

Does anyone know how to solve this problem?

Thanks,
Uriel

**Comment by luckiezhou** [comment]
It seems that your Boost.Python does not correctly recognize the graph initialization function (py::object makeGraph(std::string, std::string) in core/graph/graph_pywrapper.cpp)
Can you provide detailed information about your installed boost library?
And have you observed any errors during the building process of this project?

**Comment by urielsinger** [comment]
That was the problem! thank you, I missed the 'Eigen' path in the build..
